version: '3'
services:
  #
  # The LMS server that provides the familar UI on port 9000,
  # and the cli on port 9090.  3483 is the SlimProt and 1900
  # is the UPnP/Discovery mechanism.
  #
  # The first time this is accessed, it will need to be 
  # configured for the locations of the music and playlists.
  #
  lms:
    restart: unless-stopped
    image: justifiably/logitechmediaserver
    hostname: newsounds
    user: 1000:1000 # Try to run as same user as ripper
    ports:
      - "9000:9000"
      - "9090:9090"
      - "3483:3483"
      - "3483:3483/udp"
      - "1900:1900"
    volumes:
      #
      # Use the music files stored in the users Music 
      # directory. Keep all the other related files in there 
      # too.  
      #
      # For later: should we mount only flac? Or rely on LMS config to only
      # use flac? How to handle crap we only have in MP3? IIRC, we already
      # can configure LMS to only pay attention to flac if there's a pair...
      # how does it decide on equivalence?
      #
      - /home/${USER}/Music:/mnt/music:ro
      - /home/${USER}/Music/playlists:/mnt/playlists
      - /home/${USER}/Music/state:/mnt/state
      
      
  #
  # A media player on the local machine that LMS will find and
  # use for playback of the media files.  Could have multiple 
  # of these defined if there were multiple sound cards or 
  # DACs. Would need to give them different container and 
  # player names.
  #
  # Use aplay -l to find the audio OUTPUT_DEVICE.  Suspect the
  # format is card #, device #
  #
  # e.g.
  # card 0: PCH [HDA Intel PCH], device 0: VT2020 Analog [VT2020 Analog]
  # hw:0,0 is card 0, subdevice 0
  #
  squeezelite:
    restart: unless-stopped
    image: aschamberger/squeezelite
    environment:
      - PLAYER=LocalSqueeze
      - OUTPUT_DEVICE=hw:0,0
    devices:
      - "/dev/snd/:/dev/snd/"
  
  
  #
  # YAR - Yet Another Ripper
  #
  # The CD ripper that will monitor the CDROM drive for 
  # inserted audio disks.
  #
  # The ripper's /out directory is mapped to the same directory
  # that LMS looks in for media, i.e. /home/${USER}/Music
  #
  # Note, need to give the ripper container access to the
  # CDROM device and then tell it what device to use.
  #
  # USER_ID and GROUP_ID are used to set the ripped file 
  # owner:group rather than the default root:root of the
  # ripper process.  This has to be specified as the id's and 
  # not as names because within the container the user names 
  # and group names don't exist.  By default Ubuntu uses 1000
  # as the first user ID allocated, but use the 'id' command 
  # to confirm the correct id's to use.
  #
  # The LMS_HOST (i.e the service name above) and LMS_PORT are 
  # used by the ripper to be able to contact LMS and tell it 
  # to rescan the contents of /mnt/music so that the newly 
  # ripped files are detected and indexed.  If the server 
  # cannot be found, it silently times out and LMS won't know 
  # about the new files unless the use through the UI initiates
  # a rescan.
  #
  ripper:
    restart: unless-stopped
    build:
        context: ./yar
    environment: 
      - CDROM=/dev/sr0
      - USER_ID=1000
      - GROUP_ID=1000
      - LMS_HOST=lms
      - LMS_CLI_PORT=9090
    volumes:
      - /home/${USER}/Music:/out:rw
    devices:
      - "/dev/sr0:/dev/sr0"
      

  #
  # Mirror flac files to the spcified formats.
  #
  # Periodically scans the /flac directory for flac
  # files that don't exist in the target format directories.
  #
  flac_mirror:
    restart: unless-stopped
    user: 1000:1000 # Should run as same user as ripper
    build:
        context: ./flac-mirror
    environment: 
      # 
      # A comma seperated list of what formats to mirror to.  
      # NOTE: make sure that there is an appropriate volume mapped 
      # for the file type to somewhere outside the container otherwise the
      # mirrored files will be created inside the container where
      # no one will be able to see them!
      #
      #- MIRROR=M4A
      - MIRROR=mp3
      #
      # ffmpeg mirroring options that can be over-ridden
      #
      # - OGG_OPTIONS=-c:a libvorbis
      # - M4A_OPTIONS=-c:a aac -b:a 192k -vn
      # - MP3_OPTIONS=-c:a mp3 -ab 192k -map_metadata 0
    volumes:
      - /home/${USER}/Music:/flac:ro
      - /home/${USER}/Music/mp3:/mp3:rw
      - /home/${USER}/Music/m4a:/m4a:rw
      - /home/${USER}/Music/ogg:/ogg:rw
